# Generated by Django 5.0.6 on 2024-05-13 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicePlanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicePlanner.resource')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicePlanner.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='resources_required',
            field=models.ManyToManyField(through='ServicePlanner.ServiceResource', to='ServicePlanner.resource'),
        ),
    ]
