# Generated by Django 5.0.6 on 2024-05-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicePlanner', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
