# Generated by Django 5.0.6 on 2024-05-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicePlanner', '0004_rename_name_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
