# Generated by Django 5.0.6 on 2024-05-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicePlanner', '0005_alter_customer_email_alter_customer_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicePlanner.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='ServicePlanner.service')),
                ('similar_services_recommended', models.ManyToManyField(blank=True, related_name='similar_services_history', to='ServicePlanner.service')),
            ],
        ),
    ]
