# Generated by Django 5.0.6 on 2024-05-14 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicePlanner', '0006_servicehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicePlanner.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_services', to='ServicePlanner.service')),
            ],
        ),
    ]
