# Generated by Django 5.0.6 on 2024-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicePlanner', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='cluster_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
